### PR TITLE
modified css file

### PR DESCRIPTION
**Pull request by overmind1980**
i modified file :)

### CODE REVIEW

**Comment by eyesofjeremy** [comment]
Er, are these changes to existing CSS files?

**Comment by mezzoblue** [comment]
Nearest I can tell, it's an attempt to provide alternate CSS files that use a specific [Chinese script font](https://zh.wikipedia.org/wiki/隶书). However, without any explanation I don't know why this would be useful or worth the extra work of trying to integrate it with the [Chinese translations](http://www.csszengarden.com/tr/zh-tw/)

**Comment by eyesofjeremy** [comment]
Ahh. Interesting!

I tried inspecting one of the relevant designs and adding a `font-family: 隶书` declaration. It did change to a different font which perhaps is a better default for Chinese characters? Agreed, not sure of the value compared to the effort.

@overmind1980 IF your goal is to provide a better default font for Chinese, you might try a different approach instead:

1. Create a suitable bit of CSS that works for all relevant designs, using more specific selectors.
2. Name your file as lang.css, e.g., 'zh-cn.css'.
3. Propose changes to lang.php to check for this file in the /lang/ folder, and include the file if it exists.

@mezzoblue I'm just making this up. Not sure if you'd want to support this. :)

**Comment by overmind1980** [comment]
Thank you!
I am studying csszengarden,I consider it very great design!!!
@eyesofjeremy,thank you for you suggest! i will rename it.
specific selectors is a way showing usage of selectors.

**Comment by mezzoblue** [comment]
This Pull Request just doesn't explain itself well enough. To consider merging, I'd need:

- An explanation of why this is necessary. Also an explanation of why the existing Chinese translations aren't adequate.
- Proper integration with the site's existing language switching methods, as described by @eyesofjeremy above.

**Pull request closed without merging**
